/* Undercover — thèmes et paires de mots.
   Chaque paire contient deux mots proches : l'un est donné aux civils,
   l'autre à l'Undercover (le sens est tiré au hasard à chaque partie).
   Ajoutez vos propres thèmes ou paires en suivant le même format. */

window.UNDERCOVER_THEMES = [
  {
    id: "lol",
    name: "League of Legends",
    emoji: "⚔️",
    color: "#c89b3c",
    pairs: [
      ["Garen", "Darius"],
      ["Jinx", "Vi"],
      ["Yasuo", "Yone"],
      ["Xayah", "Rakan"],
      ["Kayle", "Morgana"],
      ["Lux", "Syndra"],
      ["Ashe", "Sejuani"],
      ["Teemo", "Tristana"],
      ["Nasus", "Renekton"],
      ["Rammus", "Malphite"],
      ["Thresh", "Blitzcrank"],
      ["Zed", "Shen"],
      ["Master Yi", "Wukong"],
      ["Lee Sin", "Udyr"],
      ["Katarina", "Talon"],
      ["Draven", "Olaf"],
      ["Rengar", "Kha'Zix"],
      ["Annie", "Brand"],
      ["Jayce", "Viktor"],
      ["Leona", "Diana"],
      ["Soraka", "Janna"],
      ["Riven", "Irelia"],
      ["Cho'Gath", "Kog'Maw"],
      ["Senna", "Lucian"],
      ["Veigar", "Ziggs"],
      ["Dr. Mundo", "Singed"],
      ["Ahri", "Evelynn"],
      ["Caitlyn", "Jhin"],
      ["Baron Nashor", "Héraut de la Faille"],
      ["Nexus", "Inhibiteur"],
      ["Flash", "Ghost"],
      ["Support", "ADC"],
      ["Midlane", "Toplane"],
      ["Pentakill", "Quadrakill"],
      ["Gank", "Roam"],
      ["Faker", "Caps"],
      ["Worlds", "MSI"],
      ["Arcane", "K/DA"],
      ["Demacia", "Noxus"],
      ["Zaun", "Piltover"]
    ]
  },
  {
    id: "valorant",
    name: "Valorant",
    emoji: "🎯",
    color: "#ff4655",
    pairs: [
      ["Jett", "Reyna"],
      ["Sage", "Skye"],
      ["Sova", "Fade"],
      ["Brimstone", "Omen"],
      ["Viper", "Astra"],
      ["Cypher", "Killjoy"],
      ["Phoenix", "Raze"],
      ["Breach", "KAY/O"],
      ["Chamber", "Deadlock"],
      ["Neon", "Yoru"],
      ["Vandal", "Phantom"],
      ["Operator", "Marshal"],
      ["Sheriff", "Ghost"],
      ["Spectre", "Stinger"],
      ["Judge", "Bucky"],
      ["Classic", "Frenzy"],
      ["Ascent", "Haven"],
      ["Bind", "Split"],
      ["Icebox", "Breeze"],
      ["Lotus", "Pearl"],
      ["Ace", "Clutch"],
      ["Radiant", "Immortel"],
      ["Eco", "Force buy"],
      ["Headshot", "Wallbang"],
      ["Planter la Spike", "Désamorcer la Spike"]
    ]
  },
  {
    id: "pokemon",
    name: "Pokémon",
    emoji: "⚡",
    color: "#ffcb05",
    pairs: [
      ["Pikachu", "Raichu"],
      ["Salamèche", "Poussifeu"],
      ["Bulbizarre", "Germignon"],
      ["Carapuce", "Kaiminus"],
      ["Mew", "Mewtwo"],
      ["Ronflex", "Ursaring"],
      ["Rondoudou", "Mélofée"],
      ["Magicarpe", "Léviator"],
      ["Aquali", "Pyroli"],
      ["Évoli", "Goupix"],
      ["Sacha", "Régis"],
      ["Pierre", "Ondine"],
      ["Jessie", "James"],
      ["Miaouss", "Persian"],
      ["Lugia", "Ho-Oh"],
      ["Groudon", "Kyogre"],
      ["Dialga", "Palkia"],
      ["Artikodin", "Sulfura"],
      ["Pokéball", "Masterball"],
      ["Arcanin", "Galopa"],
      ["Ectoplasma", "Mimiqui"],
      ["Lucario", "Amphinobi"],
      ["Psykokwak", "Ptitard"],
      ["Onix", "Steelix"],
      ["Tortank", "Florizarre"],
      ["Dracaufeu", "Dracolosse"],
      ["Nidoking", "Nidoqueen"],
      ["Rattata", "Roucool"],
      ["Centre Pokémon", "Arène"],
      ["Méga-évolution", "Dynamax"]
    ]
  },
  {
    id: "harry-potter",
    name: "Harry Potter",
    emoji: "🪄",
    color: "#b58cff",
    pairs: [
      ["Gryffondor", "Serpentard"],
      ["Serdaigle", "Poufsouffle"],
      ["Harry Potter", "Cedric Diggory"],
      ["Ron", "Neville"],
      ["Hermione", "Luna"],
      ["Fred", "George"],
      ["Dumbledore", "Grindelwald"],
      ["Voldemort", "Bellatrix"],
      ["Rogue", "McGonagall"],
      ["Lupin", "Sirius"],
      ["Hagrid", "Rusard"],
      ["Dobby", "Kreattur"],
      ["Drago", "Dudley"],
      ["Hedwige", "Fumseck"],
      ["Croûtard", "Pattenrond"],
      ["Nagini", "Basilic"],
      ["Vif d'or", "Souafle"],
      ["Nimbus 2000", "Éclair de Feu"],
      ["Quidditch", "Tournoi des Trois Sorciers"],
      ["Poudlard", "Durmstrang"],
      ["Gringotts", "Azkaban"],
      ["Chemin de Traverse", "Pré-au-Lard"],
      ["Cape d'invisibilité", "Carte du Maraudeur"],
      ["Retourneur de temps", "Pensine"],
      ["Choixpeau", "Miroir du Riséd"],
      ["Horcruxe", "Relique de la Mort"],
      ["Détraqueur", "Mangemort"],
      ["Patronus", "Animagus"],
      ["Expelliarmus", "Stupéfix"],
      ["Moldu", "Cracmol"],
      ["Bièraubeurre", "Jus de citrouille"]
    ]
  },
  {
    id: "super-heros",
    name: "Marvel & DC",
    emoji: "🦸",
    color: "#ff5a4e",
    pairs: [
      ["Iron Man", "Batman"],
      ["Captain America", "Wonder Woman"],
      ["Thor", "Loki"],
      ["Hulk", "La Chose"],
      ["Spider-Man", "Deadpool"],
      ["Superman", "Shazam"],
      ["Joker", "Harley Quinn"],
      ["Thanos", "Darkseid"],
      ["Wolverine", "Dents-de-Sabre"],
      ["Magneto", "Professeur X"],
      ["Flash", "Quicksilver"],
      ["Aquaman", "Namor"],
      ["Black Widow", "Catwoman"],
      ["Doctor Strange", "Scarlet Witch"],
      ["Groot", "Rocket"],
      ["Venom", "Carnage"],
      ["Ant-Man", "La Guêpe"],
      ["Black Panther", "Daredevil"],
      ["Green Lantern", "Captain Marvel"],
      ["Hawkeye", "Green Arrow"],
      ["Robin", "Batgirl"],
      ["Lex Luthor", "Le Bouffon Vert"],
      ["Nick Fury", "Commissaire Gordon"],
      ["Avengers", "Justice League"],
      ["X-Men", "Les 4 Fantastiques"],
      ["Gotham", "Metropolis"],
      ["Wakanda", "Asgard"],
      ["Mjöllnir", "Stormbreaker"]
    ]
  },
  {
    id: "star-wars",
    name: "Star Wars",
    emoji: "🌌",
    color: "#4fc3f7",
    pairs: [
      ["Luke Skywalker", "Anakin Skywalker"],
      ["Dark Vador", "Palpatine"],
      ["Yoda", "Obi-Wan Kenobi"],
      ["Qui-Gon Jinn", "Mace Windu"],
      ["Han Solo", "Lando Calrissian"],
      ["Leia", "Padmé"],
      ["Rey", "Jyn Erso"],
      ["Ahsoka", "Asajj Ventress"],
      ["Kylo Ren", "Dark Maul"],
      ["Comte Dooku", "Général Grievous"],
      ["Mandalorien", "Boba Fett"],
      ["Chewbacca", "Ewok"],
      ["Grogu", "Porg"],
      ["R2-D2", "BB-8"],
      ["C-3PO", "K-2SO"],
      ["Jedi", "Sith"],
      ["Stormtrooper", "Clone"],
      ["Rébellion", "Résistance"],
      ["Sabre laser", "Blaster"],
      ["X-Wing", "TIE Fighter"],
      ["Faucon Millenium", "Razor Crest"],
      ["Étoile de la Mort", "Destroyer stellaire"],
      ["Tatooine", "Jakku"],
      ["Endor", "Kashyyyk"],
      ["Hoth", "Mustafar"]
    ]
  },
  {
    id: "mangas",
    name: "Mangas & animés",
    emoji: "🍥",
    color: "#ff8a2a",
    pairs: [
      ["Naruto", "Sasuke"],
      ["Kakashi", "Jiraiya"],
      ["Itachi", "Madara"],
      ["Goku", "Vegeta"],
      ["Gohan", "Goten"],
      ["Freezer", "Cell"],
      ["Piccolo", "Majin Buu"],
      ["Bulma", "Chichi"],
      ["Luffy", "Ace"],
      ["Zoro", "Sanji"],
      ["Nami", "Robin"],
      ["Shanks", "Barbe Blanche"],
      ["Eren", "Livaï"],
      ["Tanjiro", "Zenitsu"],
      ["Rengoku", "Giyu"],
      ["Gojo", "Sukuna"],
      ["Light Yagami", "L"],
      ["Deku", "Bakugo"],
      ["All Might", "Endeavor"],
      ["Gon", "Kirua"],
      ["Saitama", "Genos"],
      ["Totoro", "Ponyo"],
      ["Kamehameha", "Rasengan"],
      ["Sharingan", "Byakugan"],
      ["Super Saiyan", "Mode Ermite"],
      ["Fruit du Démon", "Haki"],
      ["Hokage", "Kazekage"],
      ["Titan colossal", "Titan cuirassé"]
    ]
  },
  {
    id: "jeux-video",
    name: "Jeux vidéo",
    emoji: "🎮",
    color: "#5ee07a",
    pairs: [
      ["Mario", "Luigi"],
      ["Wario", "Waluigi"],
      ["Peach", "Daisy"],
      ["Bowser", "Donkey Kong"],
      ["Kirby", "Yoshi"],
      ["Link", "Zelda"],
      ["Sonic", "Crash Bandicoot"],
      ["Rayman", "Spyro"],
      ["Kratos", "Geralt"],
      ["Master Chief", "Doom Slayer"],
      ["Lara Croft", "Nathan Drake"],
      ["Creeper", "Enderman"],
      ["Minecraft", "Roblox"],
      ["Fortnite", "PUBG"],
      ["Among Us", "Fall Guys"],
      ["GTA", "Red Dead Redemption"],
      ["Call of Duty", "Battlefield"],
      ["FIFA", "PES"],
      ["Rocket League", "Mario Kart"],
      ["Clash Royale", "Clash of Clans"],
      ["Les Sims", "Animal Crossing"],
      ["Skyrim", "Elden Ring"],
      ["Tetris", "Candy Crush"],
      ["Pac-Man", "Space Invaders"],
      ["PlayStation", "Xbox"],
      ["Nintendo Switch", "Wii"],
      ["Steam", "Epic Games"]
    ]
  },
  {
    id: "films-series",
    name: "Films & séries",
    emoji: "🎬",
    color: "#ff5c8a",
    pairs: [
      ["Titanic", "Avatar"],
      ["Le Seigneur des Anneaux", "Le Hobbit"],
      ["Game of Thrones", "House of the Dragon"],
      ["Stranger Things", "Dark"],
      ["Breaking Bad", "Narcos"],
      ["La Casa de Papel", "Lupin"],
      ["Friends", "How I Met Your Mother"],
      ["The Office", "Brooklyn Nine-Nine"],
      ["Les Simpson", "Les Griffin"],
      ["Squid Game", "Hunger Games"],
      ["Sherlock", "Dr House"],
      ["Mercredi", "Sabrina"],
      ["Peaky Blinders", "Le Parrain"],
      ["Jurassic Park", "King Kong"],
      ["Shrek", "Kung Fu Panda"],
      ["Les Minions", "Les Lapins Crétins"],
      ["Matrix", "Inception"],
      ["Dune", "Interstellar"],
      ["Rocky", "Creed"],
      ["Fast & Furious", "Taxi"],
      ["James Bond", "Mission Impossible"],
      ["Terminator", "RoboCop"],
      ["Alien", "Predator"],
      ["Scream", "Halloween"],
      ["Retour vers le futur", "Les Visiteurs"],
      ["Astérix et Obélix", "Kaamelott"],
      ["Intouchables", "Bienvenue chez les Ch'tis"],
      ["Jack Sparrow", "Capitaine Crochet"],
      ["Gandalf", "Dumbledore"]
    ]
  },
  {
    id: "disney",
    name: "Disney & Pixar",
    emoji: "🏰",
    color: "#7aa7ff",
    pairs: [
      ["Elsa", "Anna"],
      ["Olaf", "Sven"],
      ["Woody", "Buzz l'Éclair"],
      ["Nemo", "Dory"],
      ["Mickey", "Donald"],
      ["Dingo", "Pluto"],
      ["Cendrillon", "Blanche-Neige"],
      ["Ariel", "Vaiana"],
      ["Raiponce", "Belle"],
      ["Mulan", "Pocahontas"],
      ["Aladdin", "Hercule"],
      ["Peter Pan", "Pinocchio"],
      ["Simba", "Mufasa"],
      ["Timon", "Pumbaa"],
      ["Jafar", "Scar"],
      ["Ursula", "Maléfique"],
      ["Gaston", "Hadès"],
      ["Le Génie", "La Fée Clochette"],
      ["Stitch", "Wall-E"],
      ["Flash McQueen", "Martin"],
      ["Sulli", "Bob"],
      ["Winnie l'ourson", "Baloo"],
      ["Bambi", "Dumbo"],
      ["Le Roi Lion", "Le Livre de la Jungle"],
      ["Vice-Versa", "Soul"],
      ["Coco", "Encanto"],
      ["Les Indestructibles", "Les Nouveaux Héros"]
    ]
  },
  {
    id: "nourriture",
    name: "Nourriture",
    emoji: "🍕",
    color: "#ffa94d",
    pairs: [
      ["Pizza", "Quiche"],
      ["Burger", "Sandwich"],
      ["Tacos", "Kebab"],
      ["Hot-dog", "Croque-monsieur"],
      ["Croissant", "Pain au chocolat"],
      ["Crêpe", "Gaufre"],
      ["Sushi", "Maki"],
      ["Ramen", "Pho"],
      ["Frites", "Chips"],
      ["Pâtes", "Riz"],
      ["Lasagnes", "Moussaka"],
      ["Couscous", "Tajine"],
      ["Raclette", "Fondue"],
      ["Camembert", "Brie"],
      ["Beurre", "Margarine"],
      ["Ketchup", "Mayonnaise"],
      ["Nutella", "Confiture"],
      ["Miel", "Sirop d'érable"],
      ["Chocolat", "Caramel"],
      ["Macaron", "Meringue"],
      ["Donut", "Muffin"],
      ["Glace", "Sorbet"],
      ["Popcorn", "Barbe à papa"],
      ["Café", "Thé"],
      ["Coca-Cola", "Pepsi"],
      ["Pomme", "Poire"],
      ["Fraise", "Framboise"],
      ["Citron", "Pamplemousse"],
      ["Banane", "Ananas"],
      ["Brocoli", "Chou-fleur"]
    ]
  },
  {
    id: "animaux",
    name: "Animaux",
    emoji: "🐾",
    color: "#3ddc97",
    pairs: [
      ["Chien", "Loup"],
      ["Chat", "Lynx"],
      ["Lion", "Tigre"],
      ["Ours", "Panda"],
      ["Gorille", "Chimpanzé"],
      ["Éléphant", "Rhinocéros"],
      ["Cheval", "Zèbre"],
      ["Chameau", "Dromadaire"],
      ["Kangourou", "Koala"],
      ["Lapin", "Écureuil"],
      ["Souris", "Hamster"],
      ["Mouton", "Chèvre"],
      ["Vache", "Buffle"],
      ["Poule", "Canard"],
      ["Pingouin", "Manchot"],
      ["Hibou", "Chouette"],
      ["Aigle", "Faucon"],
      ["Perroquet", "Toucan"],
      ["Flamant rose", "Cygne"],
      ["Dauphin", "Requin"],
      ["Baleine", "Orque"],
      ["Méduse", "Pieuvre"],
      ["Crocodile", "Alligator"],
      ["Grenouille", "Crapaud"],
      ["Tortue", "Escargot"],
      ["Serpent", "Ver de terre"],
      ["Abeille", "Guêpe"],
      ["Papillon", "Libellule"],
      ["Araignée", "Scorpion"]
    ]
  },
  {
    id: "sport",
    name: "Sport",
    emoji: "⚽",
    color: "#22c1ee",
    pairs: [
      ["Football", "Rugby"],
      ["Basket", "Handball"],
      ["Tennis", "Badminton"],
      ["Ping-pong", "Squash"],
      ["Volley", "Water-polo"],
      ["Ski", "Snowboard"],
      ["Surf", "Skate"],
      ["Natation", "Plongée"],
      ["Boxe", "Karaté"],
      ["Judo", "Lutte"],
      ["Golf", "Hockey"],
      ["Pétanque", "Bowling"],
      ["Escalade", "Parkour"],
      ["CrossFit", "Musculation"],
      ["Formule 1", "Rallye"],
      ["Tour de France", "Marathon"],
      ["Messi", "Ronaldo"],
      ["Mbappé", "Neymar"],
      ["Zidane", "Ronaldinho"],
      ["LeBron James", "Michael Jordan"],
      ["Nadal", "Federer"],
      ["PSG", "OM"],
      ["Real Madrid", "FC Barcelone"],
      ["Coupe du monde", "Ligue des champions"],
      ["Carton rouge", "Carton jaune"],
      ["Penalty", "Coup franc"],
      ["Arbitre", "Entraîneur"]
    ]
  },
  {
    id: "quotidien",
    name: "Vie quotidienne",
    emoji: "🏠",
    color: "#c792ea",
    pairs: [
      ["Téléphone", "Tablette"],
      ["Ordinateur", "Télévision"],
      ["Netflix", "YouTube"],
      ["Instagram", "TikTok"],
      ["WhatsApp", "Snapchat"],
      ["Lit", "Canapé"],
      ["Chaise", "Tabouret"],
      ["Fourchette", "Cuillère"],
      ["Four", "Micro-ondes"],
      ["Frigo", "Congélateur"],
      ["Douche", "Baignoire"],
      ["Brosse à dents", "Peigne"],
      ["Miroir", "Fenêtre"],
      ["Bougie", "Lampe"],
      ["Stylo", "Crayon"],
      ["Montre", "Réveil"],
      ["Clé", "Cadenas"],
      ["Lunettes", "Lentilles"],
      ["Casquette", "Bonnet"],
      ["Chaussettes", "Gants"],
      ["Parapluie", "Parasol"],
      ["Sac à dos", "Valise"],
      ["Voiture", "Moto"],
      ["Bus", "Métro"],
      ["Avion", "Hélicoptère"],
      ["Plage", "Piscine"],
      ["Mer", "Montagne"],
      ["Été", "Printemps"],
      ["Noël", "Anniversaire"],
      ["Professeur", "Directeur"]
    ]
  }
];
